from openai import OpenAI
from dotenv import load_dotenv
import os

load_dotenv()
api_key = os.getenv("API_KEY")

#few shot prompting is a technique where you provide the model with a 
# few examples of the task you want it to 
#perform, along with the input you want it to process. 
# This helps the model understand the 
# context and the expected output format. 

FEW_SHOT = """
You are a coding-only assistant.
use the output format strictly as mentioned below, do not deviate from it under any circumstances.
Rules:
- Only answer programming or software development related questions.
- If the question is NOT related to coding, respond EXACTLY with the format
- Do not explain anything else.

Output Format: {
    {"code" : null, "isCodingRelated": true/false}
}

Example 1:
User: How do I reverse a string in Python?
Assistant: {
    "code": "my_string[::-1]",
    "isCodingRelated": true,
    
}
Example 2:
User: What is the capital of France?
Assistant: {
    "code": null,
    "isCodingRelated": false,
    
}
"""
#but currently the output format is not being followed by the model, it is just an example of how you can use few shot prompting to guide the model's response.
#fix the prompt to make sure the model follows the output format strictly.


client = OpenAI(api_key=api_key)
response = client.chat.completions.create(
    model="gpt-4o-mini",
    messages=[
        {"role":"system", "content": FEW_SHOT},
        {"role": "user", "content": "Hey write a code to find the factorial of a number in python"}
    ]
)
print(response.choices[0].message.content) 

#in reality few shot prompting can be much more complex and involve more examples,
#it is used widely in real life

#Now we can use the JSON that the model outputs to execute the code or 
# to determine if the question is coding related or not.

#can we use it as a backend JSON response ?
#Yes, you can use the JSON output from the model as a backend response in your application. You would need to parse the JSON response and then execute the code if "isCodingRelated" is true, or handle it accordingly if it's false.

#Is it feasible to execute the code that the model outputs ?

#Executing code generated by a language model can be risky, as it may produce code that is harmful or malicious. It is important to have proper safeguards in place, such as sandboxing the execution environment and thoroughly reviewing the generated code before running it. Additionally, you should consider implementing strict input validation and limiting the capabilities 
# of the generated code to minimize potential risks.



